### ISSUE TITLE
Kubernetes free?

### ISSUE THREAD

**Issue by lstrgar** [IBM/Blockchain-for-maintaining-Digital-Assets#5]
I am having difficulty seeing how to setup a free kubernetes instance. I've setup a free IBM cloud account, but it appears kubernetes is not available. See the attached screenshot. 

<img width="1635" alt="Screen Shot 2020-01-22 at 5 00 59 PM" src="https://user-images.githubusercontent.com/16822502/72948041-d89f4180-3d38-11ea-97c4-607879f649d5.png">

**Comment by sandhya-nayak** [comment]
Free IBM Cloud Kubernetes clusters are not available with the Lite(Free) account. You will have to upgrade to a Pay-As-You-Go account (which requires you to add credit card details that can cover any charges that you may incur). 
However, once you have that Pay-As-You-Go account, you will be able to create a Free IBM Cloud Kubernetes cluster (which you will have to recreate every 30 days). If you deploy IBM Blockchain Platform service to this cluster, then your credit card shouldn't be charged.

As you can see in the image below, which shows the details of the Pay-As-You-Go plan, "There's no minimum charge. You pay only for what you use."

In addition, you also get a $200 credit which you can use to create and explore other services that are not Free.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/8854447/72985206-720b3980-3db3-11ea-8af4-81dc08f47720.png">
