### ISSUE TITLE
Outdated tutorial after 2.5 version release

### ISSUE THREAD

**Issue by n0rbs** [IBM/Blockchain-for-maintaining-Digital-Assets#6]
Please revise this tutorial. After the latest release, 2.5, some of the instructions here are outdated. Please refer to this documentation, https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-build-network

**Comment by sandhya-nayak** [comment]
@n0rbs I've started working on the updates for this pattern.

**Comment by bmos299** [comment]
Also, think about not creating the network but simply point to https://cloud.ibm.com/docs/blockchain?topic=blockchain-ibp-console-build-network, as this is supported.
